# -*- coding: utf-8 -*-
"""Multi-Agent Research Assistant using RAG and LLMs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ACwrQ--WocsAPKL1N5Rrmbm63zBRxWvS
"""

!pip install langgraph
!pip install langchain
!pip install langchain-openai
!pip install faiss-cpu
!pip install sentence-transformers
!pip install arxiv
!pip install streamlit
!pip install pydantic

from langchain_core.prompts import ChatPromptTemplate

planner_prompt = ChatPromptTemplate.from_template("""
You are a research planner.

Break this topic into research tasks.

Topic:
{topic}
""")

topic = "Hallucination reduction in LLMs"

def planner_agent(state):
    print("Planner running...")

    return {
        **state,
        "papers": []
    }

def critic_agent(state):
    print("Critic running...")

    return {
        **state,
        "critique": "Analysis is reasonable but lacks citations."
    }

def report_agent(state):

    report = f"# Research Report\n\n"

    report += f"Topic: {state['topic']}\n\n"

    report += "## Papers Found\n\n"

    for paper in state["papers"]:
        report += f"- {paper['title']}\n"

    report += f"\n## Analysis\n{state['analysis']}\n"

    return {
        **state,
        "report": report
    }

!pip install pymupdf

import requests

def download_pdf(url, filename):

    r = requests.get(url)

    with open(filename, "wb") as f:
        f.write(r.content)

import fitz

def extract_pdf_text(path):

    doc = fitz.open(path)

    text = ""

    for page in doc:
        text += page.get_text()

    return text

def chunk_text(text, size=1000):

    chunks = []

    for i in range(0, len(text), size):
        chunks.append(text[i:i+size])

    return chunks

from sentence_transformers import SentenceTransformer

embedder = SentenceTransformer(
    "BAAI/bge-small-en-v1.5"
)

import arxiv

def search_agent(state):
    print("Searching arXiv...")

    search = arxiv.Search(
        query=state["topic"],
        max_results=5
    )

    client = arxiv.Client()

    papers = []

    for paper in client.results(search):
        papers.append({
            "title": paper.title,
            "summary": paper.summary,
            "pdf_url": paper.pdf_url
        })

    return {
        **state,
        "papers": papers
    }

!pip install transformers accelerate sentencepiece -q

from transformers import pipeline

llm = pipeline(
    "text-generation",
    model="microsoft/Phi-3-mini-4k-instruct",
    device_map="auto"
)

from langgraph.graph import StateGraph, END
import json
import re

def analyze_agent(state):
    print("Analyzing papers with Phi-3 (generating table)...")

    table_header = "| Main Findings | Common Techniques | Limitations | Future Research Directions |\n"
    table_separator = "|---|---|---|---|" # Fixed: Removed trailing newline
    table_rows = []

    for paper in state["papers"]:
        paper_summary = paper["summary"]
        # Updated prompt for strict JSON output wrapped in ```json
        extraction_prompt = f"""
You are an AI research analyst. Your ONLY task is to extract information into a JSON object.
Extract the following information from the paper summary below:
- Main Findings
- Common Techniques
- Limitations
- Future Research Directions

Paper Summary:
{paper_summary}

Your response MUST be a valid JSON object. It MUST be wrapped in triple backticks and 'json' specifier (```json ... ```). DO NOT include ANY other text, explanations, or markdown outside this block. The JSON object must have the exact keys: "main_findings", "common_techniques", "limitations", "future_directions". Each value MUST be a list of strings.

```json
"""
        response = llm(
            extraction_prompt,
            max_new_tokens=200, # Temporarily reduced for faster debugging
            do_sample=False,
            temperature=0.0
        )
        full_generated_text = response[0]["generated_text"]

        extracted_data = {
            "main_findings": ["N/A"],
            "common_techniques": ["N/A"],
            "limitations": ["N/A"],
            "future_directions": ["N/A"]
        }

        try:
            json_match = re.search(r'```json\s*({.*?})\s*```', full_generated_text, re.DOTALL)
            if json_match:
                json_str = json_match.group(1)
                extracted_data = json.loads(json_str)
            else:
                # Robust fallback for truncated JSON, or if LLM only started with ```json
                if full_generated_text.strip().startswith('```json'):
                    json_str_candidate = full_generated_text.strip()[len('```json'):].strip()
                    if json_str_candidate.endswith('```'):
                        json_str_candidate = json_str_candidate[:-len('```')].strip()
                    extracted_data = json.loads(json_str_candidate)
                else:
                    raise ValueError("No complete '```json```' block found, and no leading '```json' for partial parse.")
        except (json.JSONDecodeError, ValueError) as e:
            print(f"Error parsing JSON from LLM: {e}")
            print(f"Full Generated Text (for debug): {full_generated_text[:500]}...") # Print first 500 chars for debugging
            # Fallback will use N/A values already initialized

        # Format bullet points for markdown table cells, replace newlines for single line display
        main_findings = "<br>".join(extracted_data.get("main_findings", ["N/A"])) if extracted_data.get("main_findings") else "N/A"
        common_techniques = "<br>".join(extracted_data.get("common_techniques", ["N/A"])) if extracted_data.get("common_techniques") else "N/A"
        limitation = "<br>".join(extracted_data.get("limitations", ["N/A"])) if extracted_data.get("limitations") else "N/A" # Corrected key to 'limitations'
        future_directions = "<br>".join(extracted_data.get("future_directions", ["N/A"])) if extracted_data.get("future_directions") else "N/A"

        table_rows.append(f"| {main_findings} | {common_techniques} | {limitation} | {future_directions} |")

    full_table = table_header + table_separator + "\n".join(table_rows)

    return {
        **state,
        "analysis": full_table
    }

workflow = StateGraph(ResearchState)

workflow.add_node("planner", planner_agent)
workflow.add_node("search", search_agent)
workflow.add_node("analyze", analyze_agent)
workflow.add_node("critic", critic_agent)
workflow.add_node("report", report_agent)
workflow.add_node("retrieve", retrieval_agent)

workflow.set_entry_point("planner")

workflow.add_edge("planner", "search")
workflow.add_edge("search", "retrieve")
workflow.add_edge("retrieve", "analyze")
workflow.add_edge("analyze", "critic")
workflow.add_edge("critic", "report")
workflow.add_edge("report", END)

"""## End-to-End Demo: Research Agent with Table Analysis"""

graph = workflow.compile()

# Recompile the graph after modifying analyze_agent
graph = workflow.compile()

result = graph.invoke({
    "topic": "Hallucination reduction in LLMs",
    "papers": [],
    "analysis": "",
    "critique": "",
    "report": ""
})

print(result["analysis"])

import torch

print(torch.cuda.is_available())

if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))

def chunk_text(text, chunk_size=2000):

    chunks = []

    for i in range(0, len(text), chunk_size):
        chunks.append(text[i:i+chunk_size])

    return chunks

import faiss
import numpy as np

dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)

index.add(
    np.array(embeddings).astype("float32")
)

print(index.ntotal)

def retrieve(query, k=3):

    query_embedding = embedder.encode([query])

    D, I = index.search(
        np.array(query_embedding).astype("float32"),
        k
    )

    retrieved = []

    for idx in I[0]:
        retrieved.append(chunks[idx])

    return retrieved

def retrieval_agent(state):

    query = state["topic"]

    query_embedding = embedder.encode([query])

    D, I = index.search(
        np.array(query_embedding).astype("float32"),
        k=3
    )

    retrieved_chunks = []

    for idx in I[0]:
        retrieved_chunks.append(chunks[idx])

    return {
        **state,
        "retrieved_chunks": retrieved_chunks
    }

from typing import TypedDict, Annotated
import operator
from langgraph.channels import LastValue

class ResearchState(TypedDict):
    topic: Annotated[str, LastValue(str)]
    papers: list
    retrieved_chunks: list
    analysis: str
    critique: str
    report: str

def analyze_agent(state):

    context = "\n\n".join(
        state["retrieved_chunks"]
    )

    prompt = f"""
You are an AI research assistant.

Context:
{context[:4000]}

Question:
{state['topic']}

Provide:
1. Main findings
2. Techniques
3. Limitations
"""

    response = llm(
        prompt,
        max_new_tokens=200,
        do_sample=False
    )

    return {
        **state,
        "analysis": response[0]["generated_text"]
    }

result = graph.invoke({
    "topic": "Hallucination reduction in LLMs",
    "papers": [],
    "retrieved_chunks": [],
    "analysis": "",
    "critique": "",
    "report": ""
})

print(result["report"])

# Run the end-to-end demo with the updated analyze_agent
result = graph.invoke({
    "topic": "Hallucination reduction in LLMs",
    "papers": [],
    "retrieved_chunks": [],
    "analysis": "",
    "critique": "",
    "report": ""
})

print(result["report"])

summaries = "\n\n".join(
    paper["summary"][:300]
    for paper in result["papers"]
)

prompt = f"""
Research paper summaries:

{summaries}

Main Findings:
"""

response = llm(
    prompt,
    max_new_tokens=150,
    do_sample=True,
    temperature=0.7
)

print(response[0]["generated_text"])

output = response[0]["generated_text"]

print("Prompt length:", len(prompt))
print("Output length:", len(output))

print(output[len(prompt):])

summaries = "\n\n".join(
    f"Paper: {paper['title']}\nSummary: {paper['summary']}"
    for paper in result["papers"]
)

prompt = f"""
You are an AI research analyst.

Below are summaries from multiple research papers.

{summaries}

Create a combined research report.

Main Findings:
Common Techniques:
Limitations:
Future Directions:
"""

response = llm(
    prompt,
    max_new_tokens=300,
    do_sample=True,
    temperature=0.7
)

output = response[0]["generated_text"]

print(output[len(prompt):])



import json

def analyze_agent(state):
    print("Analyzing papers with Phi-3 (generating table)...")

    table_header = "| Main Findings | Common Techniques | Limitations | Future Research Directions |\n"
    table_separator = "|---|---|---|---|\n"
    table_rows = []

    for paper in state["papers"]:
        paper_summary = paper["summary"]
        extraction_prompt = f"""
You are an AI research analyst.
Extract the following information from the paper summary below:
- Main Findings
- Common Techniques
- Limitations
- Future Research Directions

Paper Summary:
{paper_summary}

Format your response as a JSON object with keys: "main_findings", "common_techniques", "limitations", "future_directions". Each value should be a list of strings, with each string representing a bullet point.
"""
        response = llm(
            extraction_prompt,
            max_new_tokens=500, # Increased tokens for detailed extraction
            do_sample=False,
            temperature=0.0
        )
        generated_text = response[0]["generated_text"]

        # Attempt to parse JSON from the generated text
        try:
            json_start = generated_text.find('{')
            json_end = generated_text.rfind('}') + 1
            json_str = generated_text[json_start:json_end]
            extracted_data = json.loads(json_str)
        except (json.JSONDecodeError, ValueError) as e:
            print(f"Error parsing JSON from LLM: {e}")
            print(f"Generated text: {generated_text}")
            # Fallback in case of parsing error
            extracted_data = {
                "main_findings": ["N/A"],
                "common_techniques": ["N/A"],
                "limitations": ["N/A"],
                "future_directions": ["N/A"]
            }

        # Format bullet points for markdown table cells, replace newlines for single line display
        main_findings = "<br>".join(extracted_data.get("main_findings", ["N/A"])) if extracted_data.get("main_findings") else "N/A"
        common_techniques = "<br>".join(extracted_data.get("common_techniques", ["N/A"])) if extracted_data.get("common_techniques") else "N/A"
        limitation = "<br>".join(extracted_data.get("limitation", ["N/A"])) if extracted_data.get("limitation") else "N/A"
        future_directions = "<br>".join(extracted_data.get("future_directions", ["N/A"])) if extracted_data.get("future_directions") else "N/A"

        table_rows.append(f"| {main_findings} | {common_techniques} | {limitation} | {future_directions} |")

    full_table = table_header + table_separator + "\n".join(table_rows)

    return {
        **state,
        "analysis": full_table
    }

graph = workflow.compile()

result = graph.invoke({
    "topic": "Hallucination reduction in LLMs",
    "papers": [],
    "retrieved_chunks": [],
    "analysis": "",
    "critique": "",
    "report": ""
})

print(result["analysis"])

graph = workflow.compile()

result = graph.invoke({
    "topic": "Hallucination reduction in LLMs",
    "papers": [],
    "retrieved_chunks": [],
    "analysis": "",
    "critique": "",
    "report": ""
})

print(workflow.nodes.keys())

print(workflow.edges)

def retrieval_agent(state):
    print("RETRIEVAL NODE EXECUTED")
    ...

from langgraph.graph import StateGraph, END

workflow = StateGraph(ResearchState)

workflow.add_node("planner", planner_agent)
workflow.add_node("search", search_agent)
workflow.add_node("retrieve", retrieval_agent)
workflow.add_node("analyze", analyze_agent)
workflow.add_node("critic", critic_agent)
workflow.add_node("report", report_agent)

workflow.set_entry_point("planner")

workflow.add_edge("planner", "search")
workflow.add_edge("search", "retrieve")
workflow.add_edge("retrieve", "analyze")
workflow.add_edge("analyze", "critic")
workflow.add_edge("critic", "report")
workflow.add_edge("report", END)

graph = workflow.compile()

import inspect
print(inspect.getsource(retrieval_agent))

def retrieval_agent(state):

    print("RETRIEVAL NODE EXECUTED")

    query = state["topic"]

    query_embedding = embedder.encode([query])

    D, I = index.search(
        np.array(query_embedding).astype("float32"),
        k=3
    )

    retrieved_chunks = []

    for idx in I[0]:
        retrieved_chunks.append(chunks[idx])

    return {
        **state,
        "retrieved_chunks": retrieved_chunks
    }

